  export const dummyObject: GroupProps[] = [
    {
      group: "leo",
      groupDesc:
        "A band formed by a group of childhood friends who have learned to overcome their differences.",
      iconGroup: "munisekai/logo/leo_big",
      color: "#33aaee",
      char: [
        {
          name: "Hoshino Ichika",
          imageColor:"#33AAEE",
          birthday:"August 11",
          hobbies:["Listening to Miku songs","Admiring her cacti"],
          specialty:["Peeling apples"],
          icon: "munisekai/logo/icon/ichika",
          bodyImg: "munisekai/char/ichika",
          desc: "A unit of four childhood friends, who became estranged after various circumstances. The distance shifts between the four.",
        },
        {
          name: "Tenma Saki",
          imageColor:"#FFDD44 ",
          birthday:"May 9",
          hobbies:["Fashion & make-up videos","Beading"],
          specialty:["Hairstyling","Juggling"],
          icon: "munisekai/logo/icon/saki",
          bodyImg: "munisekai/char/saki",
          desc: "There's definitely a ton of things out there that we haven't tried out yet!",
        },
        {
          name: "Mochizuki Honami",
          imageColor:"#EE6666",
          birthday:"October 27",
          hobbies:["Walking her dog","Gardening"],
          specialty:["Housekeeping","Swimming"],
          icon: "munisekai/logo/icon/honami",
          bodyImg: "munisekai/char/honami",
          desc: "I feel like I was able to give a little bit of help so that everyone could move forward. ",
        },
        {
          name: "Hinomori Shiho",
          imageColor:"#BBDD22",
          birthday:"January 8",
          hobbies:["Going to girl band gigs","Playing bass guitar"],
          specialty:["Calligraphy"],
          icon: "munisekai/logo/icon/shiho",
          bodyImg: "munisekai/char/shiho",
          desc: "...Everyone, let's make this performance a great one. ",
        },
      ],
    },
    {
      group: "mmj",
      groupDesc:
        "A unique idol group formed by one girl with a dream, and three other girls who had given up on theirs.",
      iconGroup: "munisekai/logo/mmj_big",
      color: "#05df72",
      char: [
        {
          name: "Hanasato Minori",
          imageColor:"#FFCCAA",
          birthday:"April 14",
          hobbies:["Dance covers","Writing in her diary","Looking after animals"],
          specialty:["Coming up with catchphrases"],
          icon: "munisekai/logo/icon/minori",
          bodyImg: "munisekai/char/minori",
          desc: "More and more! Even moooore! In order to deliver hope to everyone! ",
        },
        {
          name: "Kiritani Haruka",
          imageColor:"#99CCFF",
          birthday:"October 5",
          hobbies:["Collecting penguin-themed merch"],
          specialty:["Basketball"],
          icon: "munisekai/logo/icon/haruka",
          bodyImg: "munisekai/char/haruka",
          desc: "You'll definitely become an idol who's able to deliver hope and dreams to everyone! ",
        },
        {
          name: "Momoi Airi",
          imageColor:"#FFAACC",
          birthday:"March 19",
          hobbies:["Researching idols","Shopping"],
          specialty:["Cooking","Looking after kids"],
          icon: "munisekai/logo/icon/airi",
          bodyImg: "munisekai/char/airi",
          desc: "Wouldn't it be amazing if we could deliver hope to everyone? ",
        },
        {
          name: "Hinomori Shizuku",
          imageColor:"#99EEDD",
          birthday:"December 6",
          hobbies:["Reading","Taking walks"],
          specialty:["Archery","Embroidery"],
          icon: "munisekai/logo/icon/shizuku",
          bodyImg: "munisekai/char/shizuku",
          desc: "With everyone next to me, I want to shine as my own self.",
        },
      ],
    },
    {
      group: "vbs",
      groupDesc:
        "A talented group of street artists who teamed up to surpass a legend.",
      iconGroup: "munisekai/logo/vbs_big",
      color: "#e60076",
      char: [
        {
          name: "Azusawa Kohane",
          imageColor:"#FF6699",
          birthday:"March 2",
          hobbies:["Looking after her dad's pet snake"],
          specialty:["Photography"],
          icon: "munisekai/logo/icon/kohane",
          bodyImg: "munisekai/char/kohane",
          desc: "No matter how scared I feel, and even if it feels like I can't move my legs, I'll still keep going forward...! ",
        },
        {
          name: "Shiraishi An",
          imageColor:"#00BBDD",
          birthday:"July 26",
          hobbies:["Growing mint"],
          specialty:["Making coffee and tea"],
          icon: "munisekai/logo/icon/an",
          bodyImg: "munisekai/char/an",
          desc: "We'll definitely surpass that night... We'll go beyond my father and the others' dream! ",
        },
        {
          name: "Shinonome Akito",
          imageColor:"#FF7722",
          birthday:"November 12",
          hobbies:["Fashion Styling"],
          specialty:["Beatboxing"],
          icon: "munisekai/logo/icon/akito",
          bodyImg: "munisekai/char/akito",
          desc: "There's no way I'll be satisfied with this level of skill! ",
        },
        {
          name: "Aoyagi Touya",
          imageColor:"#0077DD",
          birthday:"May 25",
          hobbies:["Reading"],
          specialty:["Piano","Violin"],
          icon: "munisekai/logo/icon/touya",
          bodyImg: "munisekai/char/touya",
          desc: "I want to surpass that night... and witness a scenery I've never seen before with my own eyes. ",
        },
      ],
    },
    {
      group: "wxs",
      groupDesc:
        "An eccentric musical show unit, proclaiming each day wonderful and rushing out to meet it head on.",
      iconGroup: "munisekai/logo/wxs_big",
      color: "#ffba00",
      char: [
        {
          name: "Tenma Tsukasa",
          imageColor:"#FFBB00",
          birthday:"May 17",
          hobbies:["Musicals","Making costumes"],
          specialty:["Striking cool poses","Piano"],
          icon: "munisekai/logo/icon/tsukasa",
          bodyImg: "munisekai/char/tsukasa",
          desc: "This is the prologue to Wonderlands x Showtime's new chapter!",
        },
        {
          name: "Otori Emu",
          imageColor:"#FF66BB",
          birthday:"September 9",
          hobbies:["Exploring the neighborhood"],
          specialty:["Acrobatics","Foodie"],
          icon: "munisekai/logo/icon/emu",
          bodyImg: "munisekai/char/emu",
          desc: "I want to make everyone around the world smile!",
        },
        {
          name: "Kusanagi Nene",
          imageColor:"#33DD99",
          birthday:"July 20",
          hobbies:["Fighting games","Movies","Musicals"],
          specialty:["Singing","Technology"],
          icon: "munisekai/logo/icon/nene",
          bodyImg: "munisekai/char/nene",
          desc: "I don't want to feel nervous anymore. I have to do whatever I can...!",
        },
        {
          name: "Kamishiro Rui",
          imageColor:"#BB88EE",
          birthday:"June 24",
          hobbies:["Planning shows","Balloon Art"],
          specialty:["Inventing"],
          icon: "munisekai/logo/icon/rui",
          bodyImg: "munisekai/char/rui",
          desc: "Now then, it's time to see what kind of a story is waiting for us.",
        },
      ],
    },
    {
      group: "25j",
      groupDesc:
        "A mysterious music circle that operates at 1:00 AM (25:00), and whose identities are shrouded in mystery.",
      iconGroup: "munisekai/logo/n25_big",
      color: "#7f22fe",
      char: [
        {
          name: "Yoisaki Kanade",
          imageColor:"#BB6688",
          birthday:"February 10",
          hobbies:["Finding new music","Movies","Manga","Anime","Art"],
          specialty:["An innate ability to accurately track time"],
          icon: "munisekai/logo/icon/kanade",
          bodyImg: "munisekai/char/kanade",
          desc: "What I can do right now... is to keep composing songs.",
        },
        {
          name: "Asahina Mafuyu",
          imageColor:"#8888CC",
          birthday:"January 27",
          hobbies:["Aquarium"],
          specialty:["Speaking English"],
          icon: "munisekai/logo/icon/mafuyu",
          bodyImg: "munisekai/char/mafuyu",
          desc: "I... can't understand anything anymore...",
        },
        {
          name: "Shinonome Ena",
          imageColor:"#CCAA88",
          birthday:"April 30",
          hobbies:["Drawing","Taking Selfies","Social Media","Egosurfing"],
          specialty:["Researching fashion accessories","Picking out the best cooking ingredients"],
          icon: "munisekai/logo/icon/ena",
          bodyImg: "munisekai/char/ena",
          desc: "All I want is just to keep improving. ",
        },
        {
          name: "Akiyama Mizuki",
          imageColor:"#DDAACC",
          birthday:"August 27",
          hobbies:["Making Videos","Collages"],
          specialty:["Redesigning clothes"],
          icon: "munisekai/logo/icon/mizuki",
          bodyImg: "munisekai/char/mizuki",
          desc: "I'm still me, but is that ok?",
        },
      ],
    },
  ];